In [1]:
import keras

Using TensorFlow backend.


In [2]:
import numpy as np
import math

In [3]:
from collections.abc import Callable,Sequence

In [4]:
from keras.layers import merge
from keras.layers.core import *
from keras.layers.recurrent import LSTM
from keras.layers import Convolution2D
from keras.models import *
from keras.layers.normalization import BatchNormalization

In [5]:
from keras_attention_block import *

In [6]:
INPUT_DIM = 32
TIME_STEPS = 20
SINGLE_ATTENTION_VECTOR = False
APPLY_ATTENTION_BEFORE_LSTM = False

In [7]:
inputs = Input(shape=(TIME_STEPS, INPUT_DIM))
attention_mul =  SelfAttention1DLayer(similarity="multiplicative",dropout_rate=0.2)(inputs)#MyLayer((20,32))(inputs)#
lstm_units = 32
#attention_mul = LSTM(lstm_units, return_sequences=False)(attention_mul)
attention_mul = Flatten()(attention_mul)
output = Dense(1, activation='sigmoid')(attention_mul)
m = Model(inputs=[inputs], outputs=output)

m.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
print(m.summary())

Tensor("self_attention1d_layer_1/dropout/mul:0", shape=(?, 20, 20), dtype=float32)
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_1 (InputLayer)         (None, 20, 32)            0         
_________________________________________________________________
self_attention1d_layer_1 (Se (None, 20, 32)            1024      
_________________________________________________________________
flatten_1 (Flatten)          (None, 640)               0         
_________________________________________________________________
dense_1 (Dense)              (None, 1)                 641       
Total params: 1,665
Trainable params: 1,665
Non-trainable params: 0
_________________________________________________________________
None


In [22]:
inputs = Input(shape=(TIME_STEPS, INPUT_DIM))
attention_mul =  MulitheadAttention()([inputs])
lstm_units = 32
attention_mul = LSTM(lstm_units, return_sequences=False)(attention_mul)
#attention_mul = Flatten()(attention_mul)
output = Dense(1, activation='sigmoid')(attention_mul)
m = Model(inputs=[inputs], outputs=output)

m.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
print(m.summary())

Tensor("batch_normalization_5/cond/Merge:0", shape=(?, 20, 32), dtype=float32)
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
input_9 (InputLayer)            (None, 20, 32)       0                                            
__________________________________________________________________________________________________
mulithead_SelfAttention1DLayeri (None, 20, 60)       1980        input_9[0][0]                    
__________________________________________________________________________________________________
lambda_9 (Lambda)               [(None, 20, 12), (No 0           mulithead_SelfAttention1DLayerinp
__________________________________________________________________________________________________
self_attention1d_layer_27 (Self (None, 20, 12)       0           lambda_9[0][0]                   
______________________________

In [8]:
m.layers[1].get_weights()[0]

array([[-0.00046962, -0.13437381,  0.29035535, ...,  0.04400176,
         0.13493097,  0.19176447],
       [-0.14431356, -0.09893544, -0.21598032, ...,  0.09675521,
        -0.16743793,  0.08992624],
       [ 0.18732589, -0.12218887,  0.23135248, ..., -0.07824141,
        -0.28115094, -0.1550377 ],
       ..., 
       [ 0.21561578,  0.23300567,  0.00976214, ...,  0.22284082,
         0.15295982, -0.29226014],
       [-0.0414699 ,  0.17344171,  0.24474695, ..., -0.11417152,
         0.18511939, -0.14973859],
       [-0.14273486, -0.25315189, -0.09541084, ...,  0.04641268,
        -0.19100825, -0.28547701]], dtype=float32)

In [9]:
#m.layers[1].get_weights()[1]

In [10]:
train_data = np.random.random((1000,20,32))

In [11]:
train_data.shape

(1000, 20, 32)

In [12]:
train_lab = np.random.randint(0,2,1000)

In [13]:
m.fit(train_data,train_lab , epochs=1, batch_size=100 )

Epoch 1/1
1000/1000 [==============================] - 1s 687us/step - loss: 0.7032 - acc: 0.4920


In [14]:
m.layers[1].get_weights()[0]

array([[ 0.00170965, -0.14133193,  0.2902357 , ...,  0.04439745,
         0.13123532,  0.1875332 ],
       [-0.14202532, -0.10331132, -0.2199593 , ...,  0.09738319,
        -0.17157863,  0.08891859],
       [ 0.19170028, -0.12526591,  0.23190276, ..., -0.08017471,
        -0.28455481, -0.15624151],
       ..., 
       [ 0.21603437,  0.22969134,  0.00710518, ...,  0.22416922,
         0.14840025, -0.29681873],
       [-0.03786365,  0.16813113,  0.24560623, ..., -0.11900105,
         0.18439926, -0.15430583],
       [-0.13633953, -0.26000744, -0.09758143, ...,  0.04672902,
        -0.1919831 , -0.28431571]], dtype=float32)

In [15]:
#m.layers[1].get_weights()[1]

In [7]:
X = 30
Y = 20

In [8]:
inputs = Input(shape=(X,Y,INPUT_DIM))
attention_mul =  SelfAttention2DLayer(output_size=(20,30),similarity="additive",d_a=10)(inputs)#MyLayer((20,32))(inputs)#
lstm_units = 32
attention_mul = Convolution2D(2,2,padding='same', activation= "relu")(attention_mul)
output = Dense(1, activation='sigmoid')(attention_mul)
m = Model(inputs=[inputs], outputs=output)

m.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
print(m.summary())

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_2 (InputLayer)         (None, 30, 20, 32)        0         
_________________________________________________________________
self_attention2d_layer_1 (Se (None, 20, 30, 32)        6320      
_________________________________________________________________
conv2d_1 (Conv2D)            (None, 20, 30, 2)         258       
_________________________________________________________________
dense_2 (Dense)              (None, 20, 30, 1)         3         
Total params: 6,581
Trainable params: 6,581
Non-trainable params: 0
_________________________________________________________________
None


In [9]:
TIME_STEPS_Q = 10

In [10]:
inputs_1 = Input(shape=(TIME_STEPS, INPUT_DIM))
inputs_Q = Input(shape=(TIME_STEPS_Q, INPUT_DIM))
inputs = [inputs_1,inputs_Q]
attention_mul =  Attention1DLayer(similarity="additive")(inputs)#MyLayer((20,32))(inputs)#
lstm_units = 32
attention_mul = LSTM(lstm_units, return_sequences=False)(attention_mul)
output = Dense(1, activation='sigmoid')(attention_mul)
m = Model(inputs=inputs, outputs=output)

m.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
print(m.summary())

__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
input_3 (InputLayer)            (None, 20, 32)       0                                            
__________________________________________________________________________________________________
input_4 (InputLayer)            (None, 10, 32)       0                                            
__________________________________________________________________________________________________
attention1d_layer_1 (Attention1 (None, 10, 32)       940         input_3[0][0]                    
                                                                 input_4[0][0]                    
__________________________________________________________________________________________________
lstm_2 (LSTM)                   (None, 32)           8320        attention1d_layer_1[0][0]        
__________

In [11]:
Xq=13
Yq=12

In [12]:
inputs_1 = Input(shape=(X,Y, INPUT_DIM))
inputs_Q = Input(shape=(Xq,Yq, INPUT_DIM))
inputs = [inputs_1,inputs_Q]
attention_mul =  Attention2DLayer(output_size=(12,13),similarity="additive")(inputs)#MyLayer((20,32))(inputs)#
lstm_units = 32
attention_mul = Convolution2D(2,2,padding='same', activation= "relu")(attention_mul)
output = Dense(1, activation='sigmoid')(attention_mul)
m = Model(inputs=inputs, outputs=output)

m.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
print(m.summary())

__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
input_5 (InputLayer)            (None, 30, 20, 32)   0                                            
__________________________________________________________________________________________________
input_6 (InputLayer)            (None, 13, 12, 32)   0                                            
__________________________________________________________________________________________________
attention2d_layer_1 (Attention2 (None, 12, 13, 32)   137136      input_5[0][0]                    
                                                                 input_6[0][0]                    
__________________________________________________________________________________________________
conv2d_2 (Conv2D)               (None, 12, 13, 2)    258         attention2d_layer_1[0][0]        
__________

In [13]:
DIM_V = 64

In [14]:
inputs_K = Input(shape=(TIME_STEPS, INPUT_DIM))
inputs_V = Input(shape=(TIME_STEPS, DIM_V))
inputs_Q = Input(shape=(TIME_STEPS_Q, INPUT_DIM))
inputs = [inputs_K,inputs_V ,inputs_Q]
attention_mul =  KeyValueAttention1DLayer(similarity="additive")(inputs)#MyLayer((20,32))(inputs)#
lstm_units = 32
attention_mul = LSTM(lstm_units, return_sequences=False)(attention_mul)
output = Dense(1, activation='sigmoid')(attention_mul)
m = Model(inputs=inputs, outputs=output)

m.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
print(m.summary())

__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
input_7 (InputLayer)            (None, 20, 32)       0                                            
__________________________________________________________________________________________________
input_8 (InputLayer)            (None, 20, 64)       0                                            
__________________________________________________________________________________________________
input_9 (InputLayer)            (None, 10, 32)       0                                            
__________________________________________________________________________________________________
key_value_attention1d_layer_1 ( (None, 10, 64)       940         input_7[0][0]                    
                                                                 input_8[0][0]                    
          

In [15]:
inputs_K = Input(shape=(X,Y, INPUT_DIM))
inputs_V = Input(shape=(X,Y, DIM_V))
inputs_Q = Input(shape=(Xq,Yq, INPUT_DIM))
inputs = [inputs_K,inputs_V,inputs_Q]
attention_mul =  KeyValueAttention2DLayer(output_size=(12,13),similarity="additive")(inputs)#MyLayer((20,32))(inputs)#
lstm_units = 32
attention_mul = Convolution2D(2,2,padding='same', activation= "relu")(attention_mul)
output = Dense(1, activation='sigmoid')(attention_mul)
m = Model(inputs=inputs, outputs=output)

m.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
print(m.summary())

__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
input_10 (InputLayer)           (None, 30, 20, 32)   0                                            
__________________________________________________________________________________________________
input_11 (InputLayer)           (None, 30, 20, 64)   0                                            
__________________________________________________________________________________________________
input_12 (InputLayer)           (None, 13, 12, 32)   0                                            
__________________________________________________________________________________________________
key_value_attention2d_layer_1 ( (None, 12, 13, 32)   137136      input_10[0][0]                   
                                                                 input_11[0][0]                   
          

In [8]:
import numpy as np

In [9]:
x = np.array([[1,2,3,3,5],[1,2,3,3,5],[1,2,3,3,5]])

In [10]:
y = np.array([[1,2,3,3,5],[1,2,3,3,5],[1,2,3,3,5]])

In [11]:
x*y

array([[ 1,  4,  9,  9, 25],
       [ 1,  4,  9,  9, 25],
       [ 1,  4,  9,  9, 25]])